#theme = "smol"
title = "ducks"
baseURL = "http://www.jeromedecoster.net/"

[params]
mainSections = ["posts"]

# Header
[menu]
  [[menu.main]]
        identifier = "posts"
        name = "Posts"
        url = "/posts/"
        weight = 1 

  [[menu.main]]
        identifier = "tags"
        name = "Tags"
        url = "/tags/"
        weight = 2
