name: React CI

on:
  push:
    branches:
    - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      run: npm install && npm run build && aws s3 sync build/ s3://stanis-freeknowledge.tech